name: Compile code

on:
  push:
    branches-ignore:
      - v1
      - master
      - development

jobs:
  build_image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: oengusio/frontend:v1
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            PROFILE=production

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
