name: Publish Production Docker image
on:
  release:
    types: [ published ]
jobs:
    push_to_registry:
        name: Push Docker image to GitHub Packages
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
              with:
                submodules: true
            # publish the sandbox package
            - name: Push production to GitHub Packages
              uses: docker/build-push-action@v1
              with:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
                registry: docker.pkg.github.com
                repository: esamarathon/oengus-webapp/oengus-frontend
                tags: sandbox
                build_args: PROFILE=sandbox
            - name: Trigger sandbox webhook
              uses: zzzze/webhook-trigger@v1.0.0
              with:
                webhook_url: ${{ secrets.SANDBOX_WEBHOOK_URL }}
            - name: Push production to GitHub Packages
              uses: docker/build-push-action@v1
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com
                  repository: esamarathon/oengus-webapp/oengus-frontend
                  tags: latest
                  build_args: PROFILE=production
            - name: Trigger prod webhook
              uses: zzzze/webhook-trigger@v1.0.0
              with:
                webhook_url: ${{ secrets.PROD_WEBHOOK_URL }}
